// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $favourite from "./routes/favourite.tsx";
import * as $future from "./routes/future.tsx";
import * as $index from "./routes/index.tsx";
import * as $interests from "./routes/interests.tsx";
import * as $special from "./routes/special.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $SpecialCounter from "./islands/SpecialCounter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/favourite.tsx": $favourite,
    "./routes/future.tsx": $future,
    "./routes/index.tsx": $index,
    "./routes/interests.tsx": $interests,
    "./routes/special.tsx": $special,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/SpecialCounter.tsx": $SpecialCounter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
